### PR TITLE
Add current dates instead of static dates

### PR DESCRIPTION
**Pull request by Im-Kal**
Hi, hope you are doing well. So in Pull Requests, you can contribute to any project ONLY if the owner of the repo approves it. You most fork the repo (create another copy) and add changes to it as commits. After that you can open a Pull Request and Github will auto-magically show the commits as changes to be made.

I have added manual current date collection as running this script after today will show inaccurate age due to being a fixed current date. I have added user inputs for the date collection. You can approve this change by Merge Pull Request

### CODE REVIEW

**Comment by Im-Kal** [comment]
:)

**Comment by iPinguu** [comment]
yeah no i havent yet, am i suppose to click "merge pull request" or "rebase and merge" ?

**Comment by Im-Kal** [comment]
Merge Pull Request

**Comment by iPinguu** [comment]
done! thanks again!

**Comment by Im-Kal** [comment]
Nice! Thanks

**Pull request merged**
